server:
  port: 8090

spring:
  datasource:
    username: root
    password:
#    url: jdbc:mysql://localhost:3306/jx3m?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    url: jdbc:p6spy:mysql://localhost:3306/jx3m?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
#    driver-class-name: com.mysql.cj.jdbc.Driver
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB



